### ISSUE TITLE
PnP/Samples/Core.RestFileUpload/ - Incorrect and/or misleading information in ReadMe

### ISSUE THREAD

**Issue by adambu** [SharePoint/PnP#1558]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!

#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior

DOC BUG:
In the Readme these statements are false or misleading:

Using the REST approach, you do not need to slice your file into pieces and can send a file up to 2 GB, but the same security time-out restrictions mentioned in the large upload sample apply here. If you really want to upload large files and you're on SharePoint Online the sliced upload is the advised approach. For on-premises or for files that can be uploaded within the security timeout window the REST approach is good one.

I have confirmed there is a hard coded size limited of 250 MB in SPO.  So for file larger than that you MUST use the chunked file approach.  Given that, there is a rather glaring absence of a "pure" rest example.  I came up with one using WebClient, but it was pretty hard, and involved some experimentation.  This example definitely left my customer with the impression that they could avoid the chunking if they used REST.  I have seen that repeated in numerous blogs on the internet.

I'm happy to provide my example, but not going to put it here because the bug report is about the ReadMe file.  If you want my complete example, let me know.

#### Observed Behavior

Any file larger than 250 megabytes uploaded with this example will result in:
Microsoft.SharePoint.Client.InvalidClientQueryException: The request message is too big. The server does not allow messages larger than 262144000 bytes.     at Microsoft.SharePoint.Client.Rest.RestService.ProcessQuery(ClientServiceHost serviceHost, Stream inputStream, IList`1 pendingDisposableContainer)

**Comment by adambu** [comment]
Just realized that I didn't make it clear that I'm talking about SPO when I say there's a hard-coded limit on the uploaded file size using this all-at-once approach.  In general we need to be more clear about the differences in SPO versus SharePoint on-prem, but this particular issue has led to some real confusion.  I think it would be good if the PnP samples led by example in clarifying the differences in the APIs (if there is such a difference).

**Comment by adambu** [comment]
Sorry, didn't mean to close the issue.

**Comment by VesaJuvonen** [comment]
thx Adam, I've just updated the readme based on your input. Your sample on doing large file uploads using REST would be absolutely also valuable for the community, if you are willing to share this. Readme has though now updated, so closing this one. Thx for the input.

**Comment by adambu** [comment]
Thanks for the note Vesa.  I think I did add the code on our SPDev blog, but it was so long ago I’ll have to check.  We haven’t had a similar case since then.

I see the change in the Introduction, but IMHO, it’s still not clear enough:

If you really want to upload large files and you're on SharePoint Online the sliced upload is the advised approach. For on-premises or for files that can be uploaded within the security timeout window the REST approach is good one.

I think it should say:

If you want to upload file over 250 MB and you’re on SharePoint Online, you MUST use the sliced upload approach.  The issue here is not the security timeout, but rather a hard file size upload limit set in the Web Application properties to which the tenant has no access.  This setting is immutable, so you will not be able to upload file larger than 250 MB unless you use the chunked file approach.

Because that is the actual fact.

I’ll just include my example here and you can do with it what you will.

Best regards,

Adam Burns
[Description: MSFT_logo_Gray DE sized SIG1.png]
Sr. Support Escalation Engineer - SharePoint development
Email: adambu@microsoft.com<mailto:adambu@microsoft.com>
Phone:   425-707-2428
Hours:  10:00am-7:00pm Pacific M - F

**Comment by VesaJuvonen** [comment]
Hi Adam,
thx for the editorial suggestion, have updated that now in. We absolutely due appreciate the shared code as well, but we can't really take code suggestions using email / issue list submissions. We would appreciate these kind of things to be shared Pull Requests, so that the contributors would get officially listed in the repository and would get also called out in our monthly contributions. Secondary reason is also the fact that since PnP is community open source initiative, we really don't have time to take care of the edits manually either. Anyway - if nothing else, it's now stored in this issue list, unless someone submits a Pull Request with the needed changes.
