### ISSUE TITLE
PNP version 2.20.1711 fails to provision workflows

### ISSUE THREAD

**Issue by pmatthews05** [SharePoint/PnP#1729]
[workflow Provisioning.zip](https://github.com/SharePoint/PnP/files/1522088/workflow.Provisioning.zip)
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Apply SharePoint workflows to lists, like previous version 2.19.1710.1

#### Observed Behavior
When applying a PNP template with workflow and .xaml file, the provisioning engine either falls over or hangs when applying the workflow.

#### Steps to Reproduce

- Create a simple workflow on a list
- Export the template using PNP powershell or C#
- On a new site apply the template using latest version 2.20.1711
- Hangs or fails to apply template.

**Comment by VesaJuvonen** [comment]
thx @pmatthews05 for reporting and providing the template for repro - that always helps a lot... for investigations. We'll have a look on this fast and hopefully get it still fixed by December, unless issue is around underlaying APIs.

**Comment by pmatthews05** [comment]
Has there been any update on this?

**Comment by jansenbe** [comment]
Should be fixed in 2.21.1712.2

**Comment by pmatthews05** [comment]
This is good news. I will attempt to test this in next day and report back.

**Comment by pmatthews05** [comment]
I can confirm that the code doesn't hangs or fall over when applying the template using 2.21.1712.2, however, the workflow doesn't sets the Workflow History List, or Task list.

I've included all my code in a gist https://gist.github.com/pmatthews05/c72c0277e08a4b55f2b67e06ce533a5f 

If you run version 2.19.1701.1 of pnp with the code, it creates correctly. 3 lists, adds the workflow, ties the workflow to the history and task list.

If you then delete the 3 lists, and run the code again using version 2.21.1712.2 of the code. It creates the 3 lists, adds the workflow, but the workflow isn't tied to the history and task list.

Lastly if you delete the 3 lists again, revert back to version 2.19.1701.1, it creates the 3 lists, adds the workflow and ties the workflow to the history and task list. 

I have two visual studio projects that are identical apart from the PNP version to test.

![workflow pnp 2 21 1712 2](https://user-images.githubusercontent.com/6736509/33904532-b7bfced2-df73-11e7-8335-3e6c53329715.PNG)
![workflow pnp 2 19 1701 1](https://user-images.githubusercontent.com/6736509/33904533-b7e57aec-df73-11e7-9e49-d8aaba631e38.PNG)

**Comment by PaoloPia** [comment]
Hi @pmatthews05,
Thanks for your feedback. Actually, in the November 2017 release of the engine, there was a bug in the workflow association properties serialization. However, I fixed that one before the December release. Thus, the bug you describe should be fixed. I will dig into your repro template and I will try to figure out what is happening. Stay tuned :-) ...

**Comment by pmatthews05** [comment]
Hi Paolo, It was the original template created from 2.19.1701.1. 
I will attempted to creat another template with the latest version of the code and try again, unfortunately it won't be today. 

Hopefully if it is a template xml issue, the new one can successfully be applied over the top. Although my sample is demo code, we have done something similar in a live environment to over 400 sites using the 2.19.1701.1 engine.

**Comment by PaoloPia** [comment]
Ok, I think it is an issue related to the XML file, exported with an old version of the engine. I will close this item in the meantime. Let me know if I need to re-open it. Thanks!

**Comment by pmatthews05** [comment]
Hi @PaoloPia ,
 I'm sorry, but this still isn't working for me. I have just created a brand new site collection as Classic team site. Created one list. Opened SharePoint designer and created a simple workflow that writes to the history list. Tested the workflow on the list to ensure it works.

I then deleted the lists and cleared the recycle bins. Then I applied the template again (without taking anything out). I got the following error message:
{"Value cannot be null.\r\nParameter name: input"}
StackTrace: 
at System.Xml.XmlReaderSettings.CreateReader(Stream input, Uri baseUri, String baseUriString, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(Stream input, XmlReaderSettings settings, String baseUri)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectWorkflows.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at PNPWorkflow.Program.ApplyProvisioningTemplate(String targetWebUrl, String userName, String password, String templatePath) in C:\Users\MrPau\documents\visual studio 2017\Projects\PNPWorkflow\PNPWorkflow\Program.cs:line 120
   
I have even tried applying the template to a brand new site collection. Still get the same error message Value cannot be null.

**Comment by PaoloPia** [comment]
Ok, let me re-open it and test it more.

**Comment by PaoloPia** [comment]
Hi @pmatthews05,
I just tested one more time the scenario and I cannot reproduce the issue. I created a workflow in a library, I defined the workflow to write in the history list and to assign a task. I exported the template (together with the history and tasks lists) and I applied it to a fresh new team classic site. The template got applied, the history and tasks lists were created, the workflow is working properly within the new site. Please, try to debug the solution. Maybe you are missing the FileConnector to read the .XAML file, or something else. Please, let me know. In the meantime, I will close this item again.

**Comment by pmatthews05** [comment]
Hi @PaoloPia,
 Thank you for your reply. It does appear that the error was me. I didn't have the latest .XAML files copying to the BIN folder when building the project.

I have since tested this using my demo and I don't seem to be having any issues with the latest version of the code. I've also understood how to correctly attach Officedevpnp.Core project and debug it. (Used to get error messages every time I built it).

Hopefully in the new year, I can try this new schema on the actual project I was having problems with at work, and then apply to all our live sites. 

Again thank you for your help on this.
